version: "3.9"
services:
  node:
    image: nutsfoundation/nuts-node:master
    environment:
      NUTS_CONFIGFILE: /opt/nuts/nuts.yaml
    ports:
      - 1323:1323
    volumes:
      - "./config/node/nuts.yaml:/opt/nuts/nuts.yaml"
      - "./data/node:/opt/nuts/data"

  admin:
    image: nutsfoundation/nuts-registry-admin-demo:master
    ports:
      - 1303:1303
    volumes:
      - "./config/admin/server.config.yaml:/app/server.config.yaml"
      - "./data/admin:/app/data"
    depends_on:
      - node

  ehr:
    image: nutsfoundation/nuts-demo-ehr:main
    ports:
      - 1304:1304
    volumes:
      - "./config/demo/server.config.yaml:/app/server.config.yaml"
      - "./data/admin:/app/admin-data:ro"
      - "./data/demo:/app/data"
    depends_on:
      - hapi
      - node

  hapi:
    image: hapiproject/hapi:v5.5.2
    environment:
      hapi.fhir.fhir_version: DSTU3
      hapi.fhir.partitioning.allow_references_across_partitions: "false"
    expose:
      - 8080
    ports:
      - 8080:8080
